[options]
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo
addons_path = addons
http_port = 8069
admin_passwd = $pbkdf2-sha512$600000$k/Je631P6X3vfc85J.TcGw$vWIFuh4sTS6Mtw/fqNAq9DWTr25dWmFSTXpZuIFor1F3NcG5UOrrdzCAEEZVnZrSE/yKEXGyw6sDtvMmeDvTvg
limit_time_real = 600
limit_time_cpu = 600
